export default {
  id: "teamorouter",
  priority: 115,
  alias: "teamorouter",
  uiAlias: "teamorouter",
  display: {
    name: "TeamoRouter",
    icon: "router",
    color: "#6366F1",
    textIcon: "TR",
    website: "https://teamorouter.com",
    notice: {
      apiKeyUrl: "https://teamorouter.com/dashboard",
      complimentaryLimits: "Complimentary Free models: deepseek-v4-flash-free (200 req/day), deepseek-v4-pro-free (50 req/day). Once exhausted, switch to paid models or failover.",
    },
  },
  category: "apikey",
  hasFree: true,
  transport: {
    baseUrl: "https://api.teamorouter.com/v1/chat/completions",
    validateUrl: "https://api.teamorouter.com/v1/models",
  },
  serviceKinds: ["llm", "image"],
  imageConfig: {
    baseUrl: "https://api.teamorouter.com/v1/images",
  },
  models: [
    { id: "deepseek-v4-flash-free", name: "DeepSeek V4 Flash (Free - 200 RPD)", isFree: true, tier: "free" },
    { id: "deepseek-v4-pro-free", name: "DeepSeek V4 Pro (Free - 50 RPD)", isFree: true, tier: "free" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "claude-sonnet-5", name: "Claude Sonnet 5" },
    { id: "claude-opus-5", name: "Claude Opus 5" },
    { id: "gpt-5.6-sol", name: "GPT-5.6 Sol" },
    { id: "gpt-5.6-terra", name: "GPT-5.6 Terra" },
    { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro" },
    { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash" },
    { id: "qwen3.8-max", name: "Qwen 3.8 Max" },
    { id: "kimi-k3", name: "Kimi K3" },
    { id: "glm-5.3", name: "GLM 5.3" },
  ],
  modelsFetcher: { url: "https://api.teamorouter.com/v1/models", type: "openai" },
  passthroughModels: true,
  features: { fetchModels: true, usage: true, usageApikey: true },
};
