export default {
  id: "tokenharbor",
  priority: 116,
  alias: "tokenharbor",
  uiAlias: "tokenharbor",
  display: {
    name: "Token Harbor",
    icon: "anchor",
    color: "#1F7A56",
    textIcon: "TH",
    website: "https://tokenharbor.ai",
    notice: {
      apiKeyUrl: "https://tokenharbor.ai/dashboard",
      freeModelsInfo: "Free models (:free) have a personal rolling 7×24-hour allowance. Enable 'Free models enabled' on your Token Harbor dashboard to activate.",
      privacyInfo: "Free routes may retain prompts/responses with user consent; paid routes remain 100% Zero Data Retention (ZDR).",
      quotaPeriod: "Rolling 7×24h",
    },
  },
  category: "apikey",
  hasFree: true,
  transport: {
    baseUrl: "https://tokenharbor.ai/v1/chat/completions",
    validateUrl: "https://tokenharbor.ai/v1/models",
  },
  serviceKinds: ["llm", "embedding"],
  embeddingConfig: {
    baseUrl: "https://tokenharbor.ai/v1/embeddings",
    authType: "apikey",
    authHeader: "bearer",
  },
  models: [
    { id: "th-orchestra", name: "TH Orchestra (Agentic Router)" },
    { id: "deepseek-chat:free", name: "DeepSeek V3 (Free)" },
    { id: "deepseek-reasoner:free", name: "DeepSeek R1 (Free)" },
    { id: "mimo-v2.5:free", name: "Xiaomi MiMo V2.5 (Free)" },
    { id: "qwen-2.5-coder-32b-instruct:free", name: "Qwen 2.5 Coder 32B (Free)" },
    { id: "llama-3.3-70b-instruct:free", name: "Llama 3.3 70B (Free)" },
    { id: "gemini-2.0-flash-exp:free", name: "Gemini 2.0 Flash (Free)" },
    { id: "deepseek-chat", name: "DeepSeek V3" },
    { id: "deepseek-reasoner", name: "DeepSeek R1" },
    { id: "claude-3-7-sonnet", name: "Claude 3.7 Sonnet" },
    { id: "claude-3-5-sonnet", name: "Claude 3.5 Sonnet" },
    { id: "claude-3-5-haiku", name: "Claude 3.5 Haiku" },
    { id: "gpt-4o", name: "GPT-4o" },
    { id: "gpt-4o-mini", name: "GPT-4o Mini" },
    { id: "o3-mini", name: "o3 Mini" },
    { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro" },
    { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash" },
    { id: "qwen3-max", name: "Qwen 3 Max" },
    { id: "qwen-2.5-72b-instruct", name: "Qwen 2.5 72B" },
    { id: "minimax-text-01", name: "MiniMax Text 01" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
  ],
  modelsFetcher: { url: "https://tokenharbor.ai/v1/models", type: "openai" },
  passthroughModels: true,
  features: { fetchModels: true, usageApikey: true },
};
