export default {
  id: "tokenharbor",
  priority: 116,
  alias: "tokenharbor",
  uiAlias: "tokenharbor",
  display: {
    name: "Token Harbor",
    icon: "anchor",
    color: "#1F7A56",
    textIcon: "TH",
    website: "https://tokenharbor.ai",
    notice: {
      apiKeyUrl: "https://tokenharbor.ai/dashboard",
      freeModelsInfo: "Free models (:free) have a personal rolling 7×24-hour allowance. Enable 'Free models enabled' on your Token Harbor dashboard to activate.",
      privacyInfo: "Free routes may retain prompts/responses with user consent; paid routes remain 100% Zero Data Retention (ZDR).",
      quotaPeriod: "Rolling 7×24h",
    },
  },
  category: "apikey",
  hasFree: true,
  transport: {
    baseUrl: "https://tokenharbor.ai/v1/chat/completions",
    validateUrl: "https://tokenharbor.ai/v1/models",
  },
  serviceKinds: ["llm", "embedding"],
  embeddingConfig: {
    baseUrl: "https://tokenharbor.ai/v1/embeddings",
    authType: "apikey",
    authHeader: "bearer",
  },
  models: [
    { id: "th-orchestra", name: "TH Orchestra (Agentic Router)" },
    { id: "deepseek-v4-flash:free", name: "DeepSeek V4 Flash (Free)" },
    { id: "mimo-v2.5:free", name: "Xiaomi MiMo V2.5 (Free)" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "claude-sonnet-5", name: "Claude Sonnet 5" },
    { id: "claude-opus-5", name: "Claude Opus 5" },
    { id: "claude-fable-5", name: "Claude Fable 5" },
    { id: "gpt-5.6-sol", name: "GPT-5.6 Sol" },
    { id: "gpt-5.6-terra", name: "GPT-5.6 Terra" },
    { id: "grok-4.6", name: "Grok 4.6" },
    { id: "kimi-k3", name: "Kimi K3" },
    { id: "glm-5.3", name: "GLM 5.3" },
    { id: "qwen3.8-max", name: "Qwen 3.8 Max" },
  ],
  modelsFetcher: { url: "https://tokenharbor.ai/v1/models", type: "openai" },
  passthroughModels: true,
  features: { fetchModels: true, usage: true, usageApikey: true },
};
